src/HeyUrl.Web/ViewModels/ErrorViewModel.cs
namespace HeyUrlChallengeCodeDotnet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/HeyUrl.Web/ViewModels/HomeViewModel.cs
using HeyUrl.Application.Dtos;
using System.Collections.Generic;

namespace HeyUrl.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<UrlResponseDto> Urls { get; set; }
        public UrlRequestDto NewUrl { get; set; }
    }
}

src/HeyUrl.Web/ViewModels/ShowViewModel.cs
using HeyUrl.Application.Dtos;
using System.Collections.Generic;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class ShowViewModel
    {
        public UrlResponseDto Url { get; set; }
        public string OriginalUrl { get; set; }
        public string CreatedAt { get; set; }
        public List<UrlDailyClicksDto> DailyClicks { get; set; }
        public List<UrlBrowserClicksDto> BrowseClicks { get; set; }
        public List<UrlPlatformClicksDto> PlatformClicks { get; set; }
    }
}

src/HeyUrl.Web/Controllers/ClickController.cs
using HeyUrl.Application.Dtos;
using HeyUrl.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Shyjus.BrowserDetection;
using System;
using System.Threading.Tasks;

namespace HeyUrl.Controllers
{
    [Route("click")]
    public class ClickController : Controller
    {
        private readonly IClickApplication _clickApplication;
        private readonly IBrowserDetector _browserDetector;

        public ClickController(IBrowserDetector browser,
            IClickApplication urlApp)
        {
            _browserDetector = browser;
            _clickApplication = urlApp;
        }

        [Route("{ShortUrl}")]
        public async Task<IActionResult> Post(Guid urlId, string ShortUrl)
        {
            var clickDto = new ClickRequestDto()
            {
                UrlId = urlId,
                ShortUrl = ShortUrl,
                Platform = new PlatformDto()
                {
                    Description = this._browserDetector.Browser.OS,
                    Browser = new BrowserDto()
                    {
                        Description = this._browserDetector.Browser.Name
                    }
                }
            };

            var result = await _clickApplication.Create(clickDto);

            return new OkObjectResult($"{result.Click.Count}, {this._browserDetector.Browser.OS}, {this._browserDetector.Browser.Name}");
        }
    }
}

src/HeyUrl.Web/Controllers/UrlsController.cs
using hey_url_challenge_code_dotnet.ViewModels;
using HeyUrl.Application.Dtos;
using HeyUrl.Application.Interfaces;
using HeyUrl.Domain.Services.Interfaces;
using HeyUrl.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shyjus.BrowserDetection;
using System;
using System.Threading.Tasks;

namespace HeyUrlChallengeCodeDotnet.Controllers
{
    [Route("/")]
    public class UrlsController : Controller
    {
        private readonly ILogger<UrlsController> _logger;
        private static readonly Random getrandom = new Random();
        private readonly IBrowserDetector browserDetector;
        private readonly IUrlShortHelper _urlHelper;
        private readonly IUrlApplication _urlApplication;

        public UrlsController(ILogger<UrlsController> logger,
            IBrowserDetector browserDetector,
            IUrlShortHelper helper,
            IUrlApplication UrlApplication)
        {
            this.browserDetector = browserDetector;
            _logger = logger;
            _urlHelper = helper;
            _urlApplication = UrlApplication;
        }

        public async Task<IActionResult> Index()
        {
            var urlBase = $"{this.Request.Scheme}/{this.Request.Host}{this.Request.Path}";
            var model = new HomeViewModel();

            model.Urls = await _urlApplication.GetAll(urlBase);
            return View(model);
        }

        [Route("stats/{shortUrl}")]
        public async Task<IActionResult> Show(Guid UrlId, string shortUrl)
        {
            var urlDto = await _urlApplication.GetById(UrlId);

            var Url = new ShowViewModel()
            {
                Url = urlDto,
                DailyClicks = urlDto.DailyClicks,
                BrowseClicks = urlDto.BrowserClicks,
                PlatformClicks = urlDto.PlatformClicks,
                CreatedAt = urlDto.CreatedAt.ToString("MMM d, yyy")
            };

            return View(Url);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Post(string currentUrl)
        {
           TempData["Notice"] = _urlApplication.Create(new UrlRequestDto() { OriginalUrl = currentUrl });

           return RedirectToAction(nameof(Index));

        }
    }
}

src/HeyUrl.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
    <script src="~/lib/materialize/js/materialize.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a class="brand-logo" asp-area="" asp-controller="Urls" asp-action="Index">HeyURL!</a>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

src/HeyUrl.Web/Views/Urls/Index.cshtml
@model HeyUrl.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

@if (TempData["Notice"] is not null)
{
    <div class="card-panel notice deep-orange">@TempData["Notice"]</div>
}


<div class="row">
    <div class="col m12">
        <form method="post">
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col m8 offset-m2 center-align">
                            <span class="card-title">Create a new short URL</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m6 offset-m2">
                            @Html.TextBox("currentUrl", "", new { @class = "validate form-control", @placeholder = "Your original URL here (you must include http or https prefix)" })
                        </div>
                        <div class="col m2">
                            <button type="submit" class="btn btn-primary">Shorten URL</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<table class="table highlight">
    <thead>
        <tr>
            <th scope="col">Short URL</th>
            <th scope="col">Original URL</th>
            <th scope="col">Created</th>
            <th scope="col">Clicks Count</th>
            <th scope="col">Stats</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var url in Model.Urls)
        {
            <tr>
                <th scope="row">@Html.ActionLink(
                                    @url.CompleteUrl,
                                    @url.ShortUrl,
                                    "click",
                                    new 
                                    {
                                        UrlId = @url.Id
                                    }, 
                                    null
                )
                </th>
                <td><a href="@url.OriginalUrl">@url.OriginalUrl</a></td>
                <td><!-- Please match the same format Feb 24, 2021 --> @url.CreatedAt.ToString("MMM d, yyy")</td>
                <td>@url.Click.Count</td>
                <td>
                    <a href="@Url.Action(url.ShortUrl, "stats",new {UrlId = @url.Id})">
                        <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
                            <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
                        </svg>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/HeyUrl.Web/Views/Urls/Show.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.ShowViewModel

@{
    ViewBag.Title = "Show";
    Layout = "_Layout";
}

<div class="row">
    <div class="col s12">
      <ul class="card-panel collection with-header">
        <li class="collection-header">
          <h4>
            Stats for <a href="@Model.Url.CompleteUrl">@Model.Url.ShortUrl</a>
          </h4>
        </li>
        <li class="collection-item">Created @Model.CreatedAt</li>
        <li class="collection-item">
          Original URL: @Model.Url.OriginalUrl
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <div class="card-panel">
        <div id="total-clicks-chart"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s6">
      <div class="card-panel">
        <div id="platforms-chart"></div>
      </div>
    </div>

    <div class="col s6">
      <div class="card-panel">
        <div id="browsers-chart"></div>
      </div>
    </div>
  </div>

  <script>
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawCharts);
    function drawTotalClicksChart() {
      var data = google.visualization.arrayToDataTable([
        ['day', 'clicks'],
      ].concat(@Json.Serialize(Model.DailyClicks.Select(e => new object[] { e.Stat, e.Clicks }))));
      var options = {
        title: 'total clicks',
        haxis: {
          title: 'day of month'
        },
        vaxis: {
          title: 'clicks'
        }
      };
      var chart = new google.visualization.AreaChart(
        document.getElementById('total-clicks-chart')
      );
      chart.draw(data, options);
    }
    function drawBrowsersChart() {
      var data = google.visualization.arrayToDataTable([
        ['browser', 'clicks'],
      ].concat(@Json.Serialize(Model.BrowseClicks.Select(e => new object[] { e.Stat, e.Clicks}))));
      var options = {
        title: 'Browsers'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('browsers-chart')
      );
      chart.draw(data, options);
    }
    function drawPlatformsChart() {
      var data = google.visualization.arrayToDataTable([
        ['platform', 'clicks'],
      ].concat(@Json.Serialize(Model.PlatformClicks.Select(e => new object[] { e.Stat, e.Clicks }))));
      var options = {
        title: 'Platform'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('platforms-chart')
      );
      chart.draw(data, options);
    }
    function drawCharts() {
      drawTotalClicksChart();
      drawBrowsersChart();
      drawPlatformsChart();
    }
  </script>